events {}

http {
    server {
        listen 8181;

        # Block root page
        location = / {
            # redirect instead:
            return 302 /share/9p25y9-6HxU7xv5GVVe7HpsTI6ToRQs6YwtB2Yt4jQ_69Cg8Uhool_g1VXPu4AW8KNw;
        }

        # Allow shared links
        location /share/ {
            proxy_pass http://192.168.1.73:2283;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Immich share page needs these to load images/assets
        location /api/ {
            proxy_pass http://192.168.1.73:2283;
            proxy_set_header Host $host;
        }

        location /assets/ {
            proxy_pass http://192.168.1.73:2283;
            proxy_set_header Host $host;
        }

        location /_app/ {
            proxy_pass http://192.168.1.73:2283;
            proxy_set_header Host $host;
        }

        # Block everything else
        location / {
            return 403;
        }

	location /auth/login {
	   return 403;
	}
    }
}
