services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://10.0.0.222 #optional
    volumes:
      - /home/kebing/media_config/jellyfin_config:/config
      - /home/kebing/media_config/jellyfin_cache:/cache
      - /home/kebing/media/tv:/media/tv
      - /home/kebing/media/movies:/media/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='America/Toronto'
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/kebing/media_config/plex_config:/config
      - /home/kebing/media/tv:/media/tv
      - /home/kebing/media/movies:/media/movies
    ports:
      - 32400:32400/tcp
      - 32469:32469/udp
    restart: unless-stopped

  # Torrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='America/Toronto'
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/kebing/media_config/qbittorrent_config:/config
      - /home/kebing/media/downloads:/media/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped


  # Automatically download tv series
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='America/Toronto'
    volumes:
      - /home/kebing/media_config/sonarr_config:/config
      - /home/kebing/media:/media       
    ports:
      - 8989:8989
    restart: unless-stopped

  # Search for torrents
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='America/Toronto'
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /home/kebing/media_config/jackett_config:/config
      - /home/kebing/media/downloads:/media/downloads
    ports:
      - 9117:9117
    restart: unless-stopped


